import { CoachBase, CoachState } from '../types/coach';

export const defaultCoaches: CoachBase[] = [
  // ============================================================
  // 顶级名帅 (6) - rating 83-95
  // ============================================================
  {
    id: 'coach_ancelotti',
    name: '安切洛蒂',
    rating: 95,
    style: 'balanced',
    attackBuff: 10,
    defenseBuff: 10,
    moraleBuff: 9,
    leagueBuff: 9,
    cupBuff: 10,
    pressureResistance: 95,
    riskBias: 1,
    stabilityBuff: 9,
  },
  {
    id: 'coach_guardiola',
    name: '瓜迪奥拉',
    rating: 94,
    style: 'possession',
    attackBuff: 14,
    defenseBuff: 6,
    moraleBuff: 7,
    leagueBuff: 10,
    cupBuff: 7,
    pressureResistance: 85,
    riskBias: 3,
    stabilityBuff: 8,
  },
  {
    id: 'coach_klopp',
    name: '克洛普',
    rating: 91,
    style: 'counter',
    attackBuff: 13,
    defenseBuff: 8,
    moraleBuff: 10,
    leagueBuff: 8,
    cupBuff: 9,
    pressureResistance: 88,
    riskBias: 5,
    stabilityBuff: 6,
  },
  {
    id: 'coach_simeone',
    name: '西蒙尼',
    rating: 88,
    style: 'defensive',
    attackBuff: 2,
    defenseBuff: 15,
    moraleBuff: 9,
    leagueBuff: 8,
    cupBuff: 8,
    pressureResistance: 92,
    riskBias: -7,
    stabilityBuff: 10,
  },
  {
    id: 'coach_arteta',
    name: '阿尔特塔',
    rating: 86,
    style: 'balanced',
    attackBuff: 9,
    defenseBuff: 9,
    moraleBuff: 8,
    leagueBuff: 8,
    cupBuff: 6,
    pressureResistance: 78,
    riskBias: 0,
    stabilityBuff: 7,
  },
  {
    id: 'coach_inzaghi',
    name: '因扎吉',
    rating: 83,
    style: 'balanced',
    attackBuff: 8,
    defenseBuff: 10,
    moraleBuff: 7,
    leagueBuff: 8,
    cupBuff: 7,
    pressureResistance: 75,
    riskBias: -1,
    stabilityBuff: 7,
  },

  // ============================================================
  // 优秀教练 (10) - rating 68-80
  // ============================================================
  {
    id: 'coach_slot',
    name: '斯洛特',
    rating: 80,
    style: 'possession',
    attackBuff: 8,
    defenseBuff: 7,
    moraleBuff: 6,
    leagueBuff: 7,
    cupBuff: 6,
    pressureResistance: 72,
    riskBias: 1,
    stabilityBuff: 6,
  },
  {
    id: 'coach_xabi',
    name: '阿隆索',
    rating: 79,
    style: 'possession',
    attackBuff: 9,
    defenseBuff: 6,
    moraleBuff: 7,
    leagueBuff: 7,
    cupBuff: 5,
    pressureResistance: 70,
    riskBias: 2,
    stabilityBuff: 5,
  },
  {
    id: 'coach_luis_enrique',
    name: '路易斯·恩里克',
    rating: 78,
    style: 'attacking',
    attackBuff: 12,
    defenseBuff: 2,
    moraleBuff: 6,
    leagueBuff: 6,
    cupBuff: 7,
    pressureResistance: 68,
    riskBias: 6,
    stabilityBuff: 3,
  },
  {
    id: 'coach_conte',
    name: '孔蒂',
    rating: 77,
    style: 'defensive',
    attackBuff: 4,
    defenseBuff: 12,
    moraleBuff: 8,
    leagueBuff: 8,
    cupBuff: 5,
    pressureResistance: 60,
    riskBias: -5,
    stabilityBuff: 6,
  },
  {
    id: 'coach_motta',
    name: '蒂亚戈·莫塔',
    rating: 76,
    style: 'balanced',
    attackBuff: 7,
    defenseBuff: 7,
    moraleBuff: 5,
    leagueBuff: 6,
    cupBuff: 5,
    pressureResistance: 66,
    riskBias: 0,
    stabilityBuff: 5,
  },
  {
    id: 'coach_flick',
    name: '弗里克',
    rating: 75,
    style: 'attacking',
    attackBuff: 11,
    defenseBuff: 3,
    moraleBuff: 6,
    leagueBuff: 6,
    cupBuff: 7,
    pressureResistance: 65,
    riskBias: 4,
    stabilityBuff: 4,
  },
  {
    id: 'coach_de_zerbi',
    name: '德泽尔比',
    rating: 74,
    style: 'possession',
    attackBuff: 10,
    defenseBuff: 1,
    moraleBuff: 5,
    leagueBuff: 5,
    cupBuff: 5,
    pressureResistance: 58,
    riskBias: 5,
    stabilityBuff: 2,
  },
  {
    id: 'coach_gasperini',
    name: '加斯佩里尼',
    rating: 73,
    style: 'attacking',
    attackBuff: 11,
    defenseBuff: -1,
    moraleBuff: 7,
    leagueBuff: 6,
    cupBuff: 6,
    pressureResistance: 70,
    riskBias: 7,
    stabilityBuff: 3,
  },
  {
    id: 'coach_postecoglou',
    name: '波斯特科格鲁',
    rating: 71,
    style: 'attacking',
    attackBuff: 10,
    defenseBuff: -3,
    moraleBuff: 8,
    leagueBuff: 5,
    cupBuff: 4,
    pressureResistance: 55,
    riskBias: 8,
    stabilityBuff: 1,
  },
  {
    id: 'coach_emery',
    name: '埃梅里',
    rating: 70,
    style: 'balanced',
    attackBuff: 6,
    defenseBuff: 6,
    moraleBuff: 5,
    leagueBuff: 6,
    cupBuff: 8,
    pressureResistance: 64,
    riskBias: 0,
    stabilityBuff: 5,
  },

  // ============================================================
  // 中等教练 (12) - rating 55-67
  // ============================================================
  {
    id: 'coach_mourinho',
    name: '穆里尼奥',
    rating: 67,
    style: 'defensive',
    attackBuff: 3,
    defenseBuff: 10,
    moraleBuff: 8,
    leagueBuff: 4,
    cupBuff: 7,
    pressureResistance: 50,
    riskBias: -6,
    stabilityBuff: 5,
  },
  {
    id: 'coach_xavi',
    name: '哈维',
    rating: 65,
    style: 'possession',
    attackBuff: 8,
    defenseBuff: -2,
    moraleBuff: 5,
    leagueBuff: 5,
    cupBuff: 3,
    pressureResistance: 45,
    riskBias: 3,
    stabilityBuff: 2,
  },
  {
    id: 'coach_conceicao',
    name: '孔塞桑',
    rating: 64,
    style: 'counter',
    attackBuff: 7,
    defenseBuff: 5,
    moraleBuff: 6,
    leagueBuff: 4,
    cupBuff: 5,
    pressureResistance: 58,
    riskBias: 3,
    stabilityBuff: 3,
  },
  {
    id: 'coach_xie_hui',
    name: '谢晖',
    rating: 63,
    style: 'attacking',
    attackBuff: 8,
    defenseBuff: -1,
    moraleBuff: 6,
    leagueBuff: 4,
    cupBuff: 3,
    pressureResistance: 52,
    riskBias: 5,
    stabilityBuff: 1,
  },
  {
    id: 'coach_choi',
    name: '崔康熙',
    rating: 62,
    style: 'balanced',
    attackBuff: 5,
    defenseBuff: 5,
    moraleBuff: 5,
    leagueBuff: 5,
    cupBuff: 4,
    pressureResistance: 60,
    riskBias: 0,
    stabilityBuff: 4,
  },
  {
    id: 'coach_wu_jingui',
    name: '吴金贵',
    rating: 61,
    style: 'defensive',
    attackBuff: 1,
    defenseBuff: 7,
    moraleBuff: 4,
    leagueBuff: 4,
    cupBuff: 3,
    pressureResistance: 56,
    riskBias: -4,
    stabilityBuff: 5,
  },
  {
    id: 'coach_dyche',
    name: '戴奇',
    rating: 60,
    style: 'defensive',
    attackBuff: -2,
    defenseBuff: 9,
    moraleBuff: 6,
    leagueBuff: 5,
    cupBuff: 2,
    pressureResistance: 70,
    riskBias: -8,
    stabilityBuff: 8,
  },
  {
    id: 'coach_hasenhuttl',
    name: '哈森许特尔',
    rating: 59,
    style: 'counter',
    attackBuff: 7,
    defenseBuff: 3,
    moraleBuff: 5,
    leagueBuff: 4,
    cupBuff: 3,
    pressureResistance: 50,
    riskBias: 4,
    stabilityBuff: 2,
  },
  {
    id: 'coach_li_xiaopeng',
    name: '李霄鹏',
    rating: 58,
    style: 'balanced',
    attackBuff: 4,
    defenseBuff: 4,
    moraleBuff: 5,
    leagueBuff: 4,
    cupBuff: 3,
    pressureResistance: 48,
    riskBias: 0,
    stabilityBuff: 3,
  },
  {
    id: 'coach_garcia',
    name: '鲁迪·加西亚',
    rating: 57,
    style: 'balanced',
    attackBuff: 5,
    defenseBuff: 4,
    moraleBuff: 4,
    leagueBuff: 4,
    cupBuff: 4,
    pressureResistance: 52,
    riskBias: 1,
    stabilityBuff: 3,
  },
  {
    id: 'coach_hao_wei',
    name: '郝伟',
    rating: 56,
    style: 'counter',
    attackBuff: 5,
    defenseBuff: 3,
    moraleBuff: 4,
    leagueBuff: 3,
    cupBuff: 3,
    pressureResistance: 46,
    riskBias: 2,
    stabilityBuff: 2,
  },
  {
    id: 'coach_chen_yang',
    name: '陈洋',
    rating: 55,
    style: 'defensive',
    attackBuff: 0,
    defenseBuff: 6,
    moraleBuff: 3,
    leagueBuff: 3,
    cupBuff: 2,
    pressureResistance: 44,
    riskBias: -3,
    stabilityBuff: 4,
  },

  // ============================================================
  // 普通教练 (4) - rating 48-54
  // ============================================================
  {
    id: 'coach_yan_dinghao',
    name: '严定皓',
    rating: 54,
    style: 'balanced',
    attackBuff: 3,
    defenseBuff: 3,
    moraleBuff: 3,
    leagueBuff: 2,
    cupBuff: 2,
    pressureResistance: 42,
    riskBias: 0,
    stabilityBuff: 2,
  },
  {
    id: 'coach_wang_baoshan',
    name: '王宝山',
    rating: 52,
    style: 'defensive',
    attackBuff: -1,
    defenseBuff: 5,
    moraleBuff: 3,
    leagueBuff: 3,
    cupBuff: 2,
    pressureResistance: 46,
    riskBias: -3,
    stabilityBuff: 4,
  },
  {
    id: 'coach_jankovic',
    name: '扬科维奇',
    rating: 50,
    style: 'counter',
    attackBuff: 4,
    defenseBuff: 2,
    moraleBuff: 3,
    leagueBuff: 2,
    cupBuff: 2,
    pressureResistance: 40,
    riskBias: 2,
    stabilityBuff: 1,
  },
  {
    id: 'coach_li_tie',
    name: '李铁',
    rating: 48,
    style: 'defensive',
    attackBuff: 0,
    defenseBuff: 4,
    moraleBuff: 2,
    leagueBuff: 2,
    cupBuff: 1,
    pressureResistance: 35,
    riskBias: -2,
    stabilityBuff: 2,
  },

  // ============================================================
  // 自由身教练 (4) - rating 50-72
  // ============================================================
  {
    id: 'coach_tuchel',
    name: '图赫尔',
    rating: 72,
    style: 'possession',
    attackBuff: 9,
    defenseBuff: 5,
    moraleBuff: 5,
    leagueBuff: 6,
    cupBuff: 8,
    pressureResistance: 58,
    riskBias: 3,
    stabilityBuff: 3,
  },
  {
    id: 'coach_allegri',
    name: '阿莱格里',
    rating: 66,
    style: 'defensive',
    attackBuff: 0,
    defenseBuff: 10,
    moraleBuff: 4,
    leagueBuff: 7,
    cupBuff: 5,
    pressureResistance: 62,
    riskBias: -6,
    stabilityBuff: 7,
  },
  {
    id: 'coach_pochettino',
    name: '波切蒂诺',
    rating: 60,
    style: 'attacking',
    attackBuff: 8,
    defenseBuff: 1,
    moraleBuff: 6,
    leagueBuff: 4,
    cupBuff: 5,
    pressureResistance: 50,
    riskBias: 4,
    stabilityBuff: 2,
  },
  {
    id: 'coach_bielsa',
    name: '贝尔萨',
    rating: 55,
    style: 'attacking',
    attackBuff: 12,
    defenseBuff: -5,
    moraleBuff: 9,
    leagueBuff: 3,
    cupBuff: 2,
    pressureResistance: 35,
    riskBias: 10,
    stabilityBuff: -2,
  },
];

/**
 * Default coach-to-team assignments.
 * Maps teamId -> coachId.
 */
export const defaultCoachAssignments: Record<string, string> = {
  // 顶级联赛 - 名帅配豪门
  real_madrid: 'coach_ancelotti',
  man_city: 'coach_guardiola',
  bayern: 'coach_flick',
  liverpool: 'coach_slot',
  barcelona: 'coach_xabi',
  arsenal: 'coach_arteta',
  inter: 'coach_inzaghi',
  psg: 'coach_luis_enrique',
  juventus: 'coach_motta',
  atletico: 'coach_simeone',
  dortmund: 'coach_klopp',
  ac_milan: 'coach_conceicao',
  chelsea: 'coach_de_zerbi',
  napoli: 'coach_conte',
  shanghai_port: 'coach_xie_hui',
  tottenham: 'coach_postecoglou',
  // 甲级联赛
  leverkusen: 'coach_gasperini',
  aston_villa: 'coach_emery',
  roma: 'coach_mourinho',
  marseille: 'coach_garcia',
  shandong: 'coach_choi',
  beijing_guoan: 'coach_wu_jingui',
  sevilla: 'coach_xavi',
  lyon: 'coach_hasenhuttl',
  // 乙级联赛
  chengdu: 'coach_li_xiaopeng',
  wuhan: 'coach_hao_wei',
  zhejiang: 'coach_chen_yang',
  southampton: 'coach_dyche',
  burnley: 'coach_yan_dinghao',
  henan: 'coach_wang_baoshan',
  tianjin: 'coach_jankovic',
  changchun: 'coach_li_tie',
};

/** IDs of coaches who start as free agents */
export const unemployedCoachIds: string[] = [
  'coach_tuchel',
  'coach_allegri',
  'coach_pochettino',
  'coach_bielsa',
];

/**
 * Create initial coach states from the default data.
 */
export function createInitialCoachStates(
  coaches: CoachBase[],
  assignments: Record<string, string>,
): Record<string, CoachState> {
  const coachToTeam: Record<string, string> = {};
  for (const [teamId, coachId] of Object.entries(assignments)) {
    coachToTeam[coachId] = teamId;
  }

  const states: Record<string, CoachState> = {};
  for (const coach of coaches) {
    const teamId = coachToTeam[coach.id] ?? null;
    states[coach.id] = {
      id: coach.id,
      currentTeamId: teamId,
      isUnemployed: teamId === null,
      unemployedSince: teamId === null ? 0 : null,
    };
  }
  return states;
}
