import { TeamBase, TeamState } from '../types/team';

export const defaultTeams: TeamBase[] = [
  // ============================================================
  // 顶级联赛 (16 teams) - 五大联赛豪门 + 中超旗舰
  // ============================================================
  {
    id: 'real_madrid',
    name: '皇家马德里',
    shortName: 'RMA',
    color: '#FEBE10',
    overall: 92,
    attack: 94,
    midfield: 91,
    defense: 88,
    stability: 90,
    depth: 93,
    reputation: 98,
    initialLeagueLevel: 1,
    expectation: 5,
  },
  {
    id: 'man_city',
    name: '曼彻斯特城',
    shortName: 'MCI',
    color: '#6CABDD',
    overall: 90,
    attack: 90,
    midfield: 93,
    defense: 86,
    stability: 88,
    depth: 92,
    reputation: 95,
    initialLeagueLevel: 1,
    expectation: 5,
  },
  {
    id: 'bayern',
    name: '拜仁慕尼黑',
    shortName: 'BAY',
    color: '#DC052D',
    overall: 89,
    attack: 88,
    midfield: 88,
    defense: 90,
    stability: 87,
    depth: 90,
    reputation: 96,
    initialLeagueLevel: 1,
    expectation: 5,
  },
  {
    id: 'liverpool',
    name: '利物浦',
    shortName: 'LIV',
    color: '#C8102E',
    overall: 87,
    attack: 91,
    midfield: 86,
    defense: 84,
    stability: 85,
    depth: 86,
    reputation: 92,
    initialLeagueLevel: 1,
    expectation: 4,
  },
  {
    id: 'barcelona',
    name: '巴塞罗那',
    shortName: 'BAR',
    color: '#A50044',
    overall: 86,
    attack: 89,
    midfield: 90,
    defense: 78,
    stability: 80,
    depth: 84,
    reputation: 95,
    initialLeagueLevel: 1,
    expectation: 4,
  },
  {
    id: 'arsenal',
    name: '阿森纳',
    shortName: 'ARS',
    color: '#EF0107',
    overall: 85,
    attack: 86,
    midfield: 85,
    defense: 84,
    stability: 84,
    depth: 83,
    reputation: 88,
    initialLeagueLevel: 1,
    expectation: 4,
  },
  {
    id: 'inter',
    name: '国际米兰',
    shortName: 'INT',
    color: '#0068A8',
    overall: 84,
    attack: 80,
    midfield: 84,
    defense: 90,
    stability: 86,
    depth: 82,
    reputation: 87,
    initialLeagueLevel: 1,
    expectation: 4,
  },
  {
    id: 'psg',
    name: '巴黎圣日耳曼',
    shortName: 'PSG',
    color: '#004170',
    overall: 83,
    attack: 90,
    midfield: 82,
    defense: 76,
    stability: 72,
    depth: 85,
    reputation: 90,
    initialLeagueLevel: 1,
    expectation: 4,
  },
  {
    id: 'juventus',
    name: '尤文图斯',
    shortName: 'JUV',
    color: '#000000',
    overall: 80,
    attack: 76,
    midfield: 80,
    defense: 86,
    stability: 84,
    depth: 78,
    reputation: 88,
    initialLeagueLevel: 1,
    expectation: 3,
  },
  {
    id: 'atletico',
    name: '马德里竞技',
    shortName: 'ATM',
    color: '#CB3524',
    overall: 79,
    attack: 72,
    midfield: 78,
    defense: 90,
    stability: 88,
    depth: 76,
    reputation: 82,
    initialLeagueLevel: 1,
    expectation: 3,
  },
  {
    id: 'dortmund',
    name: '多特蒙德',
    shortName: 'BVB',
    color: '#FDE100',
    overall: 78,
    attack: 84,
    midfield: 78,
    defense: 72,
    stability: 68,
    depth: 75,
    reputation: 80,
    initialLeagueLevel: 1,
    expectation: 3,
  },
  {
    id: 'ac_milan',
    name: 'AC米兰',
    shortName: 'ACM',
    color: '#FB090B',
    overall: 77,
    attack: 78,
    midfield: 76,
    defense: 78,
    stability: 74,
    depth: 76,
    reputation: 86,
    initialLeagueLevel: 1,
    expectation: 3,
  },
  {
    id: 'chelsea',
    name: '切尔西',
    shortName: 'CHE',
    color: '#034694',
    overall: 76,
    attack: 78,
    midfield: 76,
    defense: 74,
    stability: 62,
    depth: 82,
    reputation: 85,
    initialLeagueLevel: 1,
    expectation: 3,
  },
  {
    id: 'napoli',
    name: '那不勒斯',
    shortName: 'NAP',
    color: '#12A0D7',
    overall: 75,
    attack: 80,
    midfield: 76,
    defense: 70,
    stability: 66,
    depth: 72,
    reputation: 78,
    initialLeagueLevel: 1,
    expectation: 3,
  },
  {
    id: 'shanghai_port',
    name: '上海海港',
    shortName: 'SHP',
    color: '#E4002B',
    overall: 73,
    attack: 76,
    midfield: 72,
    defense: 70,
    stability: 72,
    depth: 70,
    reputation: 65,
    initialLeagueLevel: 1,
    expectation: 2,
  },
  {
    id: 'tottenham',
    name: '热刺',
    shortName: 'TOT',
    color: '#132257',
    overall: 72,
    attack: 78,
    midfield: 74,
    defense: 66,
    stability: 58,
    depth: 74,
    reputation: 80,
    initialLeagueLevel: 1,
    expectation: 3,
  },

  // ============================================================
  // 甲级联赛 (8 teams) - 二线强队 + 中超球队
  // ============================================================
  {
    id: 'leverkusen',
    name: '勒沃库森',
    shortName: 'LEV',
    color: '#E32221',
    overall: 68,
    attack: 72,
    midfield: 68,
    defense: 66,
    stability: 70,
    depth: 64,
    reputation: 72,
    initialLeagueLevel: 2,
    expectation: 4,
  },
  {
    id: 'aston_villa',
    name: '阿斯顿维拉',
    shortName: 'AVL',
    color: '#670E36',
    overall: 66,
    attack: 68,
    midfield: 66,
    defense: 64,
    stability: 66,
    depth: 62,
    reputation: 65,
    initialLeagueLevel: 2,
    expectation: 3,
  },
  {
    id: 'roma',
    name: '罗马',
    shortName: 'ROM',
    color: '#8E1F2F',
    overall: 64,
    attack: 66,
    midfield: 64,
    defense: 64,
    stability: 60,
    depth: 62,
    reputation: 76,
    initialLeagueLevel: 2,
    expectation: 3,
  },
  {
    id: 'marseille',
    name: '马赛',
    shortName: 'MAR',
    color: '#2FAEE0',
    overall: 62,
    attack: 64,
    midfield: 62,
    defense: 60,
    stability: 58,
    depth: 58,
    reputation: 68,
    initialLeagueLevel: 2,
    expectation: 3,
  },
  {
    id: 'shandong',
    name: '山东泰山',
    shortName: 'SDT',
    color: '#FF6B00',
    overall: 60,
    attack: 62,
    midfield: 60,
    defense: 58,
    stability: 62,
    depth: 56,
    reputation: 55,
    initialLeagueLevel: 2,
    expectation: 2,
  },
  {
    id: 'beijing_guoan',
    name: '北京国安',
    shortName: 'BGA',
    color: '#00A651',
    overall: 58,
    attack: 60,
    midfield: 58,
    defense: 56,
    stability: 56,
    depth: 54,
    reputation: 58,
    initialLeagueLevel: 2,
    expectation: 2,
  },
  {
    id: 'sevilla',
    name: '塞维利亚',
    shortName: 'SEV',
    color: '#D4002A',
    overall: 56,
    attack: 54,
    midfield: 58,
    defense: 56,
    stability: 60,
    depth: 52,
    reputation: 72,
    initialLeagueLevel: 2,
    expectation: 2,
  },
  {
    id: 'lyon',
    name: '里昂',
    shortName: 'LYO',
    color: '#1A5DAD',
    overall: 55,
    attack: 58,
    midfield: 54,
    defense: 52,
    stability: 52,
    depth: 50,
    reputation: 64,
    initialLeagueLevel: 2,
    expectation: 2,
  },

  // ============================================================
  // 乙级联赛 (8 teams) - 中超 + 小球会
  // ============================================================
  {
    id: 'chengdu',
    name: '成都蓉城',
    shortName: 'CDR',
    color: '#FF4500',
    overall: 53,
    attack: 54,
    midfield: 52,
    defense: 52,
    stability: 54,
    depth: 48,
    reputation: 42,
    initialLeagueLevel: 3,
    expectation: 3,
  },
  {
    id: 'wuhan',
    name: '武汉三镇',
    shortName: 'WHS',
    color: '#1E90FF',
    overall: 51,
    attack: 56,
    midfield: 50,
    defense: 48,
    stability: 46,
    depth: 46,
    reputation: 44,
    initialLeagueLevel: 3,
    expectation: 3,
  },
  {
    id: 'zhejiang',
    name: '浙江队',
    shortName: 'ZHE',
    color: '#228B22',
    overall: 49,
    attack: 50,
    midfield: 48,
    defense: 48,
    stability: 50,
    depth: 44,
    reputation: 40,
    initialLeagueLevel: 3,
    expectation: 2,
  },
  {
    id: 'southampton',
    name: '南安普顿',
    shortName: 'SOU',
    color: '#D71920',
    overall: 47,
    attack: 46,
    midfield: 48,
    defense: 48,
    stability: 46,
    depth: 44,
    reputation: 55,
    initialLeagueLevel: 3,
    expectation: 2,
  },
  {
    id: 'burnley',
    name: '伯恩利',
    shortName: 'BUR',
    color: '#6C1D45',
    overall: 45,
    attack: 42,
    midfield: 44,
    defense: 50,
    stability: 52,
    depth: 40,
    reputation: 48,
    initialLeagueLevel: 3,
    expectation: 2,
  },
  {
    id: 'henan',
    name: '河南队',
    shortName: 'HEN',
    color: '#DAA520',
    overall: 43,
    attack: 44,
    midfield: 42,
    defense: 44,
    stability: 44,
    depth: 38,
    reputation: 36,
    initialLeagueLevel: 3,
    expectation: 1,
  },
  {
    id: 'tianjin',
    name: '天津津门虎',
    shortName: 'TJJ',
    color: '#FF8C00',
    overall: 41,
    attack: 40,
    midfield: 42,
    defense: 42,
    stability: 40,
    depth: 36,
    reputation: 38,
    initialLeagueLevel: 3,
    expectation: 1,
  },
  {
    id: 'changchun',
    name: '长春亚泰',
    shortName: 'CCY',
    color: '#006400',
    overall: 40,
    attack: 38,
    midfield: 40,
    defense: 42,
    stability: 42,
    depth: 35,
    reputation: 34,
    initialLeagueLevel: 3,
    expectation: 1,
  },
];

/**
 * Create initial team states with default values for all dynamic properties.
 */
export function createInitialTeamStates(teams: TeamBase[]): Record<string, TeamState> {
  const states: Record<string, TeamState> = {};
  for (const team of teams) {
    states[team.id] = {
      id: team.id,
      leagueLevel: team.initialLeagueLevel,
      morale: 60,
      fatigue: 10,
      momentum: 0,
      squadHealth: 85,
      coachPressure: 10,
      currentCoachId: null,
      recentForm: [],
    };
  }
  return states;
}
